[workspace]
members = [
  "dom",
  "gfx/qcms",
  "gfx/wild_buzzard_headless",
  "gfx/wild_buzzard_renderer",
  "ipc/rust/wild_buzzard_ipc",
  "js",
  "layout",
  "memory/rust/wild_buzzard_handles",
  "modules/libpref/parser",
  "mozglue/rust/wild_buzzard_runtime",
  "netwerk/rust/wild_buzzard_net",
  "parser",
  "third_party/skv",
  "widget/rust/wild_buzzard_platform",
  "xpcom/rust/wild_buzzard_services",
]
exclude = [
  "gfx/wr",
  "security/certverifier/signature_cache",
  "security/manager/ssl/rsclientcerts",
  "security/manager/ssl/rsclientcerts-util",
  "servo/components/*",
  "testing/geckodriver",
  "testing/mozbase/rust/*",
  "testing/webdriver",
  "third_party/application-services/components/*",
  "third_party/application-services/components/support/*",
  "third_party/rust/*",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MPL-2.0"
rust-version = "1.90"
version = "0.1.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
